### PR TITLE
page: add snakemake logo

### LINKED ISSUE #66: features: add snakemake logo
Add Snakemake logo and link to supported workflow languages.

image

### PR DESCRIPTION
**Pull request by mvidalgarcia**
closes #66

image

### CODE REVIEW

**Comment by mvidalgarcia** [comment]
Should we go for the `next` branch also in `www.reana.io` as in `docs.reana.io`?

**Review by tiborsimko — APPROVED** [review]
LGTM

Please also add "snakemake" keyword to the meta tag in `templates/layout.html` to ease discoverability.

Please also display Snakemake icon before Yadage icon so as to respect the alphabetic order.

**Comment by mvidalgarcia** [comment]
> Please also add "snakemake" keyword to the meta tag in `templates/layout.html` to ease discoverability.

Keywords are not relevant anymore for browsers.

> Note: Many <meta> features just aren't used any more. For example, the keyword <meta> element (<meta name="keywords" content="fill, in, your, keywords, here">) — which is supposed to provide keywords for search engines to determine relevance of that page for different search terms — is ignored by search engines,...

Source: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#active_learning_the_descriptions_use_in_search_engines

**Comment by tiborsimko** [comment]
If keywords are totally ignored by the crawlers, then we can remove that field altogether...

**Pull request merged**
